name: Update readme with recent activity

on:
  schedule:
    - cron: '0 0 * * *' # Runs At the end of every day
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update GitHub Activity Readme"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme
